#include <stdio.h>
#include <assert.h>
#include <math.h>

int AreNear(double a, double b, double tolerance) {
    return fabs(a - b) <= tolerance;
}

double Celsius(double f)
{
  return (f - 32) * 5.0 / 9.0;
}

double Fahrenheit(double c)
{
  return c * 9.0 / 5.0 + 32;
}

int main() {
    // Este es un comentario simple
    printf("Hola mundo!\n"); // Otro comentario al final de línea

    /* Comentario
       multilínea
       bastante largo
       que debería ser eliminado */
    int x = 0;

    // Bucle para simular carga
    for (int i = 0; i < 10; i++) {
        x += i;
        printf("Valor: %d // Esto no es un comentario, es texto\n", x);
        char c = '\\'; // caracter con barra invertida
        char d = '\''; // comilla simple
        char e = '\"'; // comilla doble
        printf("Cadena con \\\" escapes y // dentro\n");
    }

    /* Otro comentario muy largo para molestar
       Lorem ipsum dolor sit amet, consectetur adipiscing elit.
       Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
       Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
       ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
       in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
       Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
       deserunt mollit anim id est laborum.
    */

    //assert(AreNear(Celsius(-40), -40, 0.1));
    assert(AreNear(Fahrenheit(-40), -40, 0.1));

    assert(AreNear(Celsius(14), -10, 0.1));
    //assert(AreNear(Fahrenheit(-10), 14, 0.1));

    assert(AreNear(Celsius(158), 70, 0.1));
    /*assert(AreNear(Fahrenheit(70), 158, 0.1));*/

    assert(AreNear(Celsius(212), 100.0, 0.1));
    assert(AreNear(Fahrenheit(100.0), 212.0, 0.1));

    /**/printf("//"/*"Prueba *Rara*" */"""""""Prueba Rara""'\"'""\"'");//Fin de prueba rara

    /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

    /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

    /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

    /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

        /* Lista de numeros primos comentados */

    // printf("Linea 1\n");
    // printf("Linea 2\n");
    // printf("Linea 3\n");
    printf("Linea 4\n");
    // printf("Linea 5\n");
    printf("Linea 6\n");
    // printf("Linea 7\n");
    printf("Linea 8\n");
    printf("Linea 9\n");
    printf("Linea 10\n");
    // printf("Linea 11\n");
    printf("Linea 12\n");
    // printf("Linea 13\n");
    printf("Linea 14\n");
    printf("Linea 15\n");
    printf("Linea 16\n");
    // printf("Linea 17\n");
    printf("Linea 18\n");
    // printf("Linea 19\n");
    printf("Linea 20\n");
    printf("Linea 21\n");
    printf("Linea 22\n");
    // printf("Linea 23\n");
    printf("Linea 24\n");
    printf("Linea 25\n");
    printf("Linea 26\n");
    printf("Linea 27\n");
    printf("Linea 28\n");
    // printf("Linea 29\n");
    printf("Linea 30\n");
    // printf("Linea 31\n");
    printf("Linea 32\n");
    printf("Linea 33\n");
    printf("Linea 34\n");
    printf("Linea 35\n");
    printf("Linea 36\n");
    // printf("Linea 37\n");
    printf("Linea 38\n");
    printf("Linea 39\n");
    printf("Linea 40\n");
    // printf("Linea 41\n");
    printf("Linea 42\n");
    // printf("Linea 43\n");
    printf("Linea 44\n");
    printf("Linea 45\n");
    printf("Linea 46\n");
    // printf("Linea 47\n");
    printf("Linea 48\n");
    printf("Linea 49\n");
    printf("Linea 50\n");
    printf("Linea 51\n");
    // printf("Linea 53\n");
    printf("Linea 52\n");
    printf("Linea 54\n");
    // printf("Linea 59\n");
    printf("Linea 55\n");
    printf("Linea 56\n");
    printf("Linea 57\n");
    printf("Linea 58\n");
    printf("Linea 60\n");
    // printf("Linea 61\n");
    printf("Linea 62\n");
    // printf("Linea 67\n");
    printf("Linea 63\n");
    printf("Linea 64\n");
    printf("Linea 65\n");
    printf("Linea 66\n");
    printf("Linea 68\n");
    printf("Linea 69\n");
    // printf("Linea 71\n");
    printf("Linea 70\n");
    printf("Linea 72\n");
    printf("Linea 73\n");
    printf("Linea 74\n");
    printf("Linea 75\n");
    // printf("Linea 73\n");
    printf("Linea 76\n");
    printf("Linea 77\n");
    printf("Linea 78\n");
    // printf("Linea 79\n");
    printf("Linea 79\n");
    printf("Linea 80\n");
    printf("Linea 81\n");
    // printf("Linea 83\n");
    printf("Linea 82\n");
    printf("Linea 84\n");
    printf("Linea 85\n");
    printf("Linea 86\n");
    // printf("Linea 89\n");
    printf("Linea 87\n");
    printf("Linea 88\n");
    printf("Linea 90\n");
    printf("Linea 91\n");
    printf("Linea 92\n");
    // printf("Linea 97\n");
    printf("Linea 93\n");
    printf("Linea 94\n");
    printf("Linea 95\n");
    printf("Linea 96\n");
    printf("Linea 98\n");
    // printf("Linea 101\n");
    printf("Linea 99\n");
    printf("Linea 100\n");
    printf("Linea 102\n");
    printf("Linea 103\n");
    // printf("Linea 103\n");
    printf("Linea 104\n");
    printf("Linea 105\n");
    printf("Linea 106\n");
    printf("Linea 107\n");
    // printf("Linea 109\n");
    printf("Linea 108\n");
    printf("Linea 110\n");
    printf("Linea 111\n");
    printf("Linea 112\n");
    // printf("Linea 113\n");
    printf("Linea 114\n");
    printf("Linea 115\n");
    printf("Linea 116\n");
    // printf("Linea 127\n");
    printf("Linea 117\n");
    printf("Linea 118\n");
    printf("Linea 119\n");
    printf("Linea 120\n");
    printf("Linea 121\n");
    // printf("Linea 127\n");
    printf("Linea 122\n");
    printf("Linea 123\n");
    printf("Linea 124\n");
    printf("Linea 125\n");
    printf("Linea 126\n");
    // printf("Linea 127\n");
    printf("Linea 128\n");
    printf("Linea 129\n");
    printf("Linea 130\n");
    printf("Linea 131\n");
    printf("Linea 132\n");
    // printf("Linea 137\n");
    printf("Linea 133\n");
    printf("Linea 134\n");
    printf("Linea 135\n");
    printf("Linea 136\n");
    printf("Linea 138\n");
    printf("Linea 139\n");
    // printf("Linea 149\n");
    printf("Linea 140\n");
    printf("Linea 141\n");
    printf("Linea 142\n");
    printf("Linea 143\n");
    printf("Linea 144\n");
    printf("Linea 145\n");
    printf("Linea 146\n");
    // printf("Linea 149\n");
    printf("Linea 147\n");
    printf("Linea 148\n");
    printf("Linea 150\n");
    printf("Linea 151\n");
    // printf("Linea 151\n");
    printf("Linea 152\n");
    printf("Linea 153\n");
    printf("Linea 154\n");
    printf("Linea 155\n");
    printf("Linea 156\n");
    // printf("Linea 157\n");
    printf("Linea 158\n");
    printf("Linea 159\n");
    printf("Linea 160\n");
    printf("Linea 161\n");
    printf("Linea 162\n");
    // printf("Linea 163\n");
    printf("Linea 164\n");
    printf("Linea 165\n");
    printf("Linea 166\n");
    printf("Linea 167\n");
    printf("Linea 168\n");
    printf("Linea 169\n");
    // printf("Linea 173\n");
    printf("Linea 170\n");
    printf("Linea 171\n");
    printf("Linea 172\n");
    printf("Linea 174\n");
    printf("Linea 175\n");
    printf("Linea 176\n");
    printf("Linea 177\n");
    printf("Linea 178\n");
    // printf("Linea 179\n");
    printf("Linea 179\n");
    printf("Linea 180\n");
    printf("Linea 181\n");
    printf("Linea 182\n");
    printf("Linea 183\n");
    printf("Linea 184\n");
    printf("Linea 185\n");
    printf("Linea 186\n");
    // printf("Linea 191\n");
    printf("Linea 187\n");
    printf("Linea 188\n");
    printf("Linea 189\n");
    printf("Linea 190\n");
    printf("Linea 192\n");
    printf("Linea 193\n");
    printf("Linea 194\n");
    printf("Linea 195\n");
    printf("Linea 196\n");
    printf("Linea 197\n");
    printf("Linea 198\n");
    printf("Linea 199\n");
    printf("Linea 200\n");

    printf("Fin del programa\n");
    return 0;
}